In [42]:
import bs4
from bs4 import BeautifulSoup
import requests

In [48]:
url="https://www.iplt20.com/auction/2022"
r=requests.get(url)
print(r)

<Response [200]>

In [49]:
soup=BeautifulSoup(r.text)
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title data-page-title="IPL 2022 Auction | Live Updates &amp; Overview | IPLT20" id="page_title">IPL 2022 Auction | Live Updates &amp; Overview | IPLT20</title>
<link href="https://www.iplt20.com/auction/2022" rel="canonical"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1.0, minimum-scale=0.5, maximum-scale=3.0" name="viewport"/>
<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> -->
<meta content="ufMVOA04dmaXklV1AmskGp181eU3t4mVD9qoZmus" name="csrf-token"/>
<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
<meta content="#19398a" name="theme-color"/>
<meta content="website" name="og:type"/>
<meta content="https://www.iplt20.com/auction/2022" name="og:url"/>
<meta content="IPL 2022 Auction | Live Updates &amp; Overview | IPLT20" property="og:title"/>
<meta content="Get live updates on the IPL 2022 player auction, including images, videos, and an overview of the bidding process. Stay informed on IPLT20." property="og:description"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="IPL 2022 Auction | Live Updates &amp; Overview | IPLT20" name="twitter:title"/>
<meta content="Get live updates on the IPL 2022 player auction, including images, videos, and an overview of the bidding process. Stay informed on IPLT20." name="twitter:description"/>
<meta content="https://www.iplt20.com/assets/images/ipl-thumbnail.png" name="twitter:image"/>
<meta content="https://www.iplt20.com/assets/images/ipl-thumbnail.png" name="og:image"/>
<meta content="https://www.iplt20.com/assets/images/ipl-thumbnail.png" name="og:image:secure_url"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link crossorigin="" href="https://documents.iplt20.com/" rel="preconnect"/>
<meta content="IPL 2025 player auction, IPL auction live updates, IPL auction images, IPL auction videos, cricket auction overview, IPL auction live, Top Buys, IPL Sold player" name="keywords"/>
<meta content="Get live updates on the IPL 2022 player auction, including images, videos, and an overview of the bidding process. Stay informed on IPLT20." name="description"/>
<link href="https://documents.iplt20.com/ipl/assets/images/favicon.ico" rel="shortcut icon"/>
<link as="style" href="https://www.iplt20.com/assets/css/bootstrap-5.3.3.min.css?v=1.19" onload="this.onload=null;this.rel='stylesheet'" rel="preload"/>
<noscript><link href="https://www.iplt20.com/assets/css/bootstrap-5.3.3.min.css?v=1.19" rel="stylesheet"/></noscript>
<!-- <link rel="preload" onload="this.onload=null;this.rel='stylesheet'" as="style" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@1,700&display=swap"> -->
<!-- <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@1,700&display=swap"></noscript> -->
<!-- <link rel="preload" onload="this.onload=null;this.rel='stylesheet'" as="style" href="https://www.iplt20.com/slick/slick.css?v=1.19 "> -->
<!-- <noscript><link rel="stylesheet" href="https://www.iplt20.com/slick/slick.css?v=1.19"></noscript> -->
<link as="style" href="https://www.iplt20.com/assets/js/mcustom/jquery.mCustomScrollbar.min.css?v=1.19" onload="this.onload=null;this.rel='stylesheet'" rel="preload"/>
<noscript><link href="https://www.iplt20.com/assets/js/mcustom/jquery.mCustomScrollbar.min.css?v=1.19" rel="stylesheet"/></noscript>
<link as="style" href="https://www.iplt20.com/assets/css/dataTables.min.css?v=1.19" onload="this.onload=null;this.rel='stylesheet'" rel="preload"/>
<link href="https://www.iplt20.com/assets/css/ipl-style.min.css?v=1.19" rel="stylesheet"/>
<link as="style" href="https://www.iplt20.com/assets/css/font-awesome.min.css?v=1.19" onload="this.onload=null;this.rel='stylesheet'" rel="preload"/>
<!-- <noscript><link rel="stylesheet" href="https://www.iplt20.com/assets/css/font-awesome.min.css?v=1.19"></noscript> -->
<noscript><link href="https://www.iplt20.com/assets/css/font-awesome.min.css?v=1.19?v=1.19" rel="stylesheet"/></noscript>
<script defer="" src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
<script>
        var AWS_S3_domain = "https://documents.iplt20.com/";
      if(/^\?fbclid=/.test(location.search))
         location.replace(location.href.replace(/\?fbclid.+/, ""));
     </script>
<style>
</style>
<script>
        var title = "IPL 2022 Auction | Live Updates & Overview | IPLT20";
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({
            'client_ga_id': '308089989',
            'content_type': title,
            'platform_type': 'web',
            'environment': 'production',
        });
    </script>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PQ2QKF4');</script>
<!-- End Google Tag Manager -->
</head>
<body>
<div ng-app="MyApp">
<header class="ap-header col-100 floatLft" id="header-main" style="display:block">
<div class="ap-stripWht py-2">
<div class="container">
<div class="d-flex justify-content-between">
<span class="ap-bcciLogo">
<!--  <a href="" target="_blank" class="text-white"><img style="width:34px" src="https://www.iplt20.com/assets/images/headeripllogo.svg" alt="IPl Logo">2023</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; -->
<a href="https://www.bcci.tv/" target="_blank"><img alt="BCCI Logo" height="22" src="https://documents.iplt20.com//ipl/assets/images/BCCI_logo.png" width="23"/>BCCI.TV</a>     |
                        <a href="https://www.wplt20.com/" target="_blank"><img alt="WPL Logo" class="m-0" height="25" src="https://documents.iplt20.com//ipl/assets/images/womens-premier-league-logonew.webp" width="45"/></a>
</span>
<span class="ap-socialDiv">
<span>Follow Us</span>
<!--  <a onclick="click_social(this)" data-title="thread" href="https://www.threads.net/@iplt20" target="_blank" class="twit">
                            <img src="https://www.iplt20.com/assets/images/thread-icon.svg" alt="threads">
                        </a> -->
<a aria-label="twitter" class="twit" data-title="twitter" href="https://twitter.com/IPL" onclick="click_social(this)" target="_blank">
<!-- <img width="24" height="24" src="https://documents.iplt20.com//ipl/assets/images/new-twitter-icon.svg" alt="twitter"> -->
</a>
<a aria-label="instagram" class="insta" data-title="instagram" href="https://www.instagram.com/iplt20/" onclick="click_social(this)" target="_blank">
<!-- <img width="24" height="24" src="https://documents.iplt20.com//ipl/assets/images/new-instagram-icon.svg" alt="instagram"> -->
</a>
<a aria-label="facebook" class="fb" data-title="facebook" href="https://www.facebook.com/IPL/" onclick="click_social(this)" target="_blank">
<!-- <img width="24" height="24" src="https://documents.iplt20.com//ipl/assets/images/new-facebook-icon.svg" alt="facebook"> -->
</a>
</span>
</div>
</div>
</div>
<div class="ap-main-header left right col-100 floatLft flexDisplay justifySpace alignCenter flxNav" id="myHeader">
<div class="container-fluid container-xl d-flex justify-content-between flex-wrap position-relative p-0">
<div class="ap-ipl-logo"><a href="https://www.iplt20.com"><img alt="" aria-label="ipl-logo-new-old" class="lazy" height="83" src="https://documents.iplt20.com//ipl/assets/images/ipl-logo-new-old.png" width="166"/></a></div>
<div class="site-mobile-menu site-navbar-target">
<div class="site-mobile-menu-header xxxxxxxxxxx">
<a class="mt-3" href="https://www.iplt20.com"><img alt="" aria-label="ipl-logo-new-old" height="83" src="https://documents.iplt20.com//ipl/assets/images/ipl-logo-new-old.png" width="166"/></a>
<div class="site-mobile-menu-close mt-3">
<span class="icon-close2 js-menu-toggle">×</span>
</div>
</div>
<div class="site-mobile-menu-body">
</div>
</div> <!-- .site-mobile-menu -->
<div class="site-navbar-wrap">
<div class="site-navbar site-navbar-target d-flex align-items-center">
<div class="align-items-center">
<nav class="site-navigation text-center">
<div class="d-lg-none ml-md-0 mr-auto"><a class="site-menu-toggle js-menu-toggle text-white d-block" href="#"><span class="icon-menu h3 d-block mb-0"><img alt="menu" aria-label="menu" height="28" src=" https://documents.iplt20.com//ipl/assets/images/new-menu.svg" width="28"/></span></a></div>
<ul class="site-menu main-menu js-clone-nav d-none d-lg-block textCenter">
<li class="has-children">
<a data-element_text="MATCHES" data-event_context="header" data-slug="matches/results" href="https://www.iplt20.com/matches/results" onclick="click_menu(this)">MATCHES</a>
</li>
<li class="has-children">
<a data-element_text="POINTS TABLE" data-event_context="header" data-slug="points-table/men" href="https://www.iplt20.com/points-table/men" onclick="click_menu(this)">POINTS TABLE</a>
</li>
<li class="has-children">
<a data-element_text="Videos" data-event_context="header" data-slug="videos" href="javascript:void(0)" onclick="click_menu(this)">VIDEOS</a>
<ul class="dropdown arrow-top">
<li class="videos/all sub_menu">
<a data-element_text="LATEST" data-event_context="header" data-slug="videos/all" data-url="videos/all" href="https://www.iplt20.com/videos/all" onclick="click_menu(this)">LATEST</a>
</li>
<li class="videos/ipl-exclusive sub_menu">
<a data-element_text="IPL EXCLUSIVE" data-event_context="header" data-slug="videos/ipl-exclusive" data-url="videos/ipl-exclusive" href="https://www.iplt20.com/videos/ipl-exclusive" onclick="click_menu(this)">IPL EXCLUSIVE</a>
</li>
<li class="videos/auction sub_menu">
<a data-element_text="Auction" data-event_context="header" data-slug="videos/auction" data-url="videos/auction" href="https://www.iplt20.com/videos/auction" onclick="click_menu(this)">AUCTION</a>
</li>
<li class="videos/ipl-magic sub_menu">
<a data-element_text="MAGIC MOMENTS" data-event_context="header" data-slug="videos/ipl-magic" data-url="videos/ipl-magic" href="https://www.iplt20.com/videos/ipl-magic" onclick="click_menu(this)">MAGIC MOMENTS</a>
</li>
<li class="videos/highlights sub_menu">
<a data-element_text="HIGHLIGHTS" data-event_context="header" data-slug="videos/highlights" data-url="videos/highlights" href="https://www.iplt20.com/videos/highlights" onclick="click_menu(this)">HIGHLIGHTS</a>
</li>
<li class="videos/interviews sub_menu">
<a data-element_text="INTERVIEWS" data-event_context="header" data-slug="videos/interviews" data-url="videos/interviews" href="https://www.iplt20.com/videos/interviews" onclick="click_menu(this)">INTERVIEWS</a>
</li>
<li class="videos/press-conference sub_menu">
<a data-element_text="PRESS CONFERENCES" data-event_context="header" data-slug="videos/press-conference" data-url="videos/press-conference" href="https://www.iplt20.com/videos/press-conference" onclick="click_menu(this)">PRESS CONFERENCES</a>
</li>
<li class="videos sub_menu">
<a data-element_text="ALL" data-event_context="header" data-slug="videos" data-url="videos" href="https://www.iplt20.com/videos" onclick="click_menu(this)">ALL</a>
</li>
</ul>
</li>
<li class="has-children">
<a data-element_text="TEAMS" data-event_context="header" data-slug="teams" href="https://www.iplt20.com/teams" onclick="click_menu(this)">TEAMS</a>
</li>
<li class="has-children">
<a data-element_text="NEWS" data-event_context="header" data-slug="news" href="javascript:void(0)" onclick="click_menu(this)">NEWS</a>
<ul class="dropdown arrow-top">
<li class="news sub_menu">
<a data-element_text="ALL NEWS" data-event_context="header" data-slug="news" data-url="news" href="https://www.iplt20.com/news" onclick="click_menu(this)">ALL NEWS</a>
</li>
<li class="news/announcements sub_menu">
<a data-element_text="ANNOUNCEMENTS" data-event_context="header" data-slug="news/announcements" data-url="news/announcements" href="https://www.iplt20.com/news/announcements" onclick="click_menu(this)">ANNOUNCEMENTS</a>
</li>
<li class="news/match-reports sub_menu">
<a data-element_text="MATCH REPORTS" data-event_context="header" data-slug="news/match-reports" data-url="news/match-reports" href="https://www.iplt20.com/news/match-reports" onclick="click_menu(this)">MATCH REPORTS</a>
</li>
</ul>
</li>
<li class="has-children">
<a data-element_text="STATS" data-event_context="header" data-slug="stats" href="javascript:void(0)" onclick="click_menu(this)">STATS</a>
<ul class="dropdown arrow-top">
<li class="stats/2025 sub_menu">
<a data-element_text="OVERALL STATS" data-event_context="header" data-slug="stats/2025" data-url="stats/2025" href="https://www.iplt20.com/stats/2025" onclick="click_menu(this)">OVERALL STATS</a>
</li>
<li class="comparison sub_menu">
<a data-element_text="HEAD TO HEAD" data-event_context="header" data-slug="comparison" data-url="comparison" href="https://www.iplt20.com/comparison" onclick="click_menu(this)">HEAD TO HEAD</a>
</li>
</ul>
</li>
<li class="active has-children">
<a data-element_text="AUCTION" data-event_context="header" data-slug="auction" href="https://www.iplt20.com/auction" onclick="click_menu(this)">AUCTION</a>
</li>
<li class="has-children">
<a data-element_text="MORE" data-event_context="header" data-slug="more" href="javascript:void(0)" onclick="click_menu(this)">MORE</a>
<ul class="dropdown arrow-top">
<li class="photos sub_menu">
<a data-element_text="PHOTOS" data-event_context="header" data-slug="photos" data-url="photos" href="https://www.iplt20.com/photos" onclick="click_menu(this)">PHOTOS</a>
</li>
<li class="mobile-products sub_menu">
<a data-element_text="MOBILE PRODUCTS" data-event_context="header" data-slug="mobile-products" data-url="mobile-products" href="https://www.iplt20.com/mobile-products" onclick="click_menu(this)">MOBILE PRODUCTS</a>
</li>
<li class="venues sub_menu">
<a data-element_text="VENUES" data-event_context="header" data-slug="venues" data-url="venues" href="https://www.iplt20.com/venues" onclick="click_menu(this)">VENUES</a>
</li>
<li class="about/about-us sub_menu">
<a data-element_text="ABOUT" data-event_context="header" data-slug="about/about-us" data-url="about/about-us" href="https://www.iplt20.com/about/about-us" onclick="click_menu(this)">ABOUT</a>
</li>
</ul>
</li>
</ul>
</nav>
</div>
</div>
</div>
<div class="ap-search">
<!-- <a href="http://fanverse.ipltt20-dev2.epicon.in/" target="_blank" class="fanverse">FANVERSE</a> -->
<!-- <a href="javascript:;" class="ap-searchClick"><img class="lazy" src="https://documents.iplt20.com//ipl/assets/images/new-search-icon.svg" alt="" style="opacity: 0;"></a> -->
<!-- <a href="javascript:;" class="ap-fanPolls" data-toggle="modal" data-target="#fan"><img class="lazy" src="https://www.iplt20.com/assets/images/fanpolls.png" alt=""></a> -->
<div class="fan-viewer">
<a class="ap-fanPolls me-3" href="https://www.iplt20.com/fan-poll"><img alt="" aria-label="fan-poll" class="lazy" height="24" src="https://documents.iplt20.com//ipl/assets/images/fan-poll.webp" width="54"/></a>
<!-- <a href="https://www.iplt20.com/fan-poll-auction" class="ap-fanPolls me-3"><img width="77" height="25" class="lazy" src="https://documents.iplt20.com//ipl/assets/images/auction-fan-poll.webp" aria-label="auction-fan-poll" alt=""></a> -->
<a class="viewers-choice-head ms-0" href="https://www.iplt20.com/polls/emerging-player"><img alt="" aria-label="viewers-choice" class="lazy" height="25" src="https://documents.iplt20.com//ipl/assets/images/viewers-choice.webp" width="79"/></a>
<!-- <a href="https://documents.iplt20.com/bcci/documents/1765197869375_TATA-IPL-2026-Auction-List-8.12.25.pdf" target="_blank" class="ap-auction-list me-3"><img width="88" height="30" class="lazy" src="https://documents.iplt20.com//ipl/assets/images/auction-list.svg"  aria-label="auction-list" alt=""></a> -->
<button class="search-icon-header-menu bg-transparent border-0" onclick="$('#searchTabForHeaderMenu').toggle();"><img alt="" aria-label="new-search-icon" class="lazy" height="22" id="searchIconHeader" src="https://documents.iplt20.com//ipl/assets/images/new-search-icon.svg" width="22"/></button>
</div>
<!-- <a href="javascript:void();" class="ap-mobile-menu-toggle">
                        <img class="lazy" src="https://www.iplt20.com/assets/images/mob-ham.png" alt="">
                    </a> -->
</div>
<div class="header-search w-100 px-0 pt-3 pb-3" id="searchTabForHeaderMenu" style="display:none;">
<!-- <div class="w-100"> -->
<form action="https://www.iplt20.com/search" class="d-flex flex-wrap" method="GET">
<select id="search_type" name="type">
<option value="all">All</option>
<option value="video">Videos</option>
<option value="news">News</option>
</select>
<input id="searchInputForHeader" minlength="2" name="text" placeholder="Search here" required="" type="text" value=""/>
<button class="btn btn-default btn-for-search p-0" id="searchButtonForHeader" onclick="searchEvent(this)" type="submit"> <i aria-hidden="true" class="fa fa-search" id="fa-search-id"></i> <b id="searchText"> Search</b></button>
<button class="closeSearchBtn" onclick="$('#searchTabForHeaderMenu').toggle();" type="button">✕</button>
</form>
<!-- </div> -->
</div>
</div>
</div>
</header>
<!-- womens ipl auction start -->
<!-- <div class="women-worldcup-main" style="display:flex">
        <div class="women-ipl-logo-live">
            <img class="will" src="https://documents.iplt20.com//ipl/assets/images/womens-premier-league-logonew.webp" width="50" height="30" alt="wpl-logo">
            <div class="line"></div>
            <button class="action-blink blink">AUCTION</button>
        </div>
        <div class="marquee-content">
            <a href="https://www.wplt20.com/auction?utm_source=ipl&utm_medium=web_banner&utm_campaign=auction26" target="_blank">
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
                <span>Click here to follow all the LIVE action from TATA WPL Auction 2026 <img src="https://www.iplt20.com/assets/images/auction-hammer.svg" width="50" height="30" alt="wpl-logo"></span>
            </a>
        </div>
    </div>  -->
<!-- womens ipl auction end -->
<!-- page blocker start -->
<!-- page blocker end -->
<script defer="" src="https://www.iplt20.com/assets/js/ipl-custom.min.js?v=1.19"></script>
<!--navigation menu end-->

In [50]:
table = soup.find("table")
table

<table class="ih-td-tab w-100 auction-tbl">
<tr class="ih-pt-tbl" style="display:revert">
<th class="skip-filter" style="width:25%;text-align: left;">SR. NO.</th>
<th class="skip-filter" style="width:25%;text-align: left;">TEAM</th>
<th class="skip-filter" style="width:25%;">FUNDS REMAINING</th>
<th class="skip-filter" style="width:25%;">OVERSEAS PLAYERS </th>
<th class="skip-filter" style="width:25%;">TOTAL PLAYERS</th>
</tr>
<tbody id="pointsdata">
<tr>
<td>1</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644311961_CSKroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Chennai Super Kings</h2>
</div>
</td>
<td>₹2,95,00,000</td>
<td>8</td>
<td>25</td>
</tr>
<tr>
<td>2</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312373_DCroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Delhi Capitals</h2>
</div>
</td>
<td>₹10,00,000</td>
<td>7</td>
<td>24</td>
</tr>
<tr>
<td>3</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1645712208_GTroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Gujarat Titans</h2>
</div>
</td>
<td>₹15,00,000</td>
<td>8</td>
<td>23</td>
</tr>
<tr>
<td>4</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312095_KKRroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Kolkata Knight Riders</h2>
</div>
</td>
<td>₹45,00,000</td>
<td>8</td>
<td>25</td>
</tr>
<tr>
<td>5</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644487352_lsgrounding.png"/>
</div>
<h2 class="ih-pt-cont">Lucknow Super Giants</h2>
</div>
</td>
<td>₹0</td>
<td>7</td>
<td>21</td>
</tr>
<tr>
<td>6</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312227_MIroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Mumbai Indians</h2>
</div>
</td>
<td>₹10,00,000</td>
<td>8</td>
<td>25</td>
</tr>
<tr>
<td>7</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312239_PBKSroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Punjab Kings</h2>
</div>
</td>
<td>₹3,45,00,000</td>
<td>7</td>
<td>25</td>
</tr>
<tr>
<td>8</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312268_RRroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Rajasthan Royals</h2>
</div>
</td>
<td>₹95,00,000</td>
<td>8</td>
<td>24</td>
</tr>
<tr>
<td>9</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312253_RCBroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Royal Challengers Bangalore</h2>
</div>
</td>
<td>₹1,55,00,000</td>
<td>8</td>
<td>22</td>
</tr>
<tr>
<td>10</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312281_SRHroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Sunrisers Hyderabad</h2>
</div>
</td>
<td>₹10,00,000</td>
<td>8</td>
<td>23</td>
</tr>
</tbody>
</table>

In [8]:
table = soup.find("tbody")
table

<tbody id="pointsdata">
<tr>
<td>1</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644311961_CSKroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Chennai Super Kings</h2>
</div>
</td>
<td>₹2,95,00,000</td>
<td>8</td>
<td>25</td>
</tr>
<tr>
<td>2</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312373_DCroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Delhi Capitals</h2>
</div>
</td>
<td>₹10,00,000</td>
<td>7</td>
<td>24</td>
</tr>
<tr>
<td>3</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1645712208_GTroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Gujarat Titans</h2>
</div>
</td>
<td>₹15,00,000</td>
<td>8</td>
<td>23</td>
</tr>
<tr>
<td>4</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312095_KKRroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Kolkata Knight Riders</h2>
</div>
</td>
<td>₹45,00,000</td>
<td>8</td>
<td>25</td>
</tr>
<tr>
<td>5</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644487352_lsgrounding.png"/>
</div>
<h2 class="ih-pt-cont">Lucknow Super Giants</h2>
</div>
</td>
<td>₹0</td>
<td>7</td>
<td>21</td>
</tr>
<tr>
<td>6</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312227_MIroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Mumbai Indians</h2>
</div>
</td>
<td>₹10,00,000</td>
<td>8</td>
<td>25</td>
</tr>
<tr>
<td>7</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312239_PBKSroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Punjab Kings</h2>
</div>
</td>
<td>₹3,45,00,000</td>
<td>7</td>
<td>25</td>
</tr>
<tr>
<td>8</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312268_RRroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Rajasthan Royals</h2>
</div>
</td>
<td>₹95,00,000</td>
<td>8</td>
<td>24</td>
</tr>
<tr>
<td>9</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312253_RCBroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Royal Challengers Bangalore</h2>
</div>
</td>
<td>₹1,55,00,000</td>
<td>8</td>
<td>22</td>
</tr>
<tr>
<td>10</td>
<td class="ih-t-color">
<div class="ih-pt-ic">
<div class="ih-pt-img" style="width: 60px">
<img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312281_SRHroundbig.png"/>
</div>
<h2 class="ih-pt-cont">Sunrisers Hyderabad</h2>
</div>
</td>
<td>₹10,00,000</td>
<td>8</td>
<td>23</td>
</tr>
</tbody>

In [51]:
rows=table.find_all("tr")
rows

[<tr class="ih-pt-tbl" style="display:revert">
 <th class="skip-filter" style="width:25%;text-align: left;">SR. NO.</th>
 <th class="skip-filter" style="width:25%;text-align: left;">TEAM</th>
 <th class="skip-filter" style="width:25%;">FUNDS REMAINING</th>
 <th class="skip-filter" style="width:25%;">OVERSEAS PLAYERS </th>
 <th class="skip-filter" style="width:25%;">TOTAL PLAYERS</th>
 </tr>,
 <tr>
 <td>1</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644311961_CSKroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Chennai Super Kings</h2>
 </div>
 </td>
 <td>₹2,95,00,000</td>
 <td>8</td>
 <td>25</td>
 </tr>,
 <tr>
 <td>2</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312373_DCroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Delhi Capitals</h2>
 </div>
 </td>
 <td>₹10,00,000</td>
 <td>7</td>
 <td>24</td>
 </tr>,
 <tr>
 <td>3</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1645712208_GTroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Gujarat Titans</h2>
 </div>
 </td>
 <td>₹15,00,000</td>
 <td>8</td>
 <td>23</td>
 </tr>,
 <tr>
 <td>4</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312095_KKRroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Kolkata Knight Riders</h2>
 </div>
 </td>
 <td>₹45,00,000</td>
 <td>8</td>
 <td>25</td>
 </tr>,
 <tr>
 <td>5</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644487352_lsgrounding.png"/>
 </div>
 <h2 class="ih-pt-cont">Lucknow Super Giants</h2>
 </div>
 </td>
 <td>₹0</td>
 <td>7</td>
 <td>21</td>
 </tr>,
 <tr>
 <td>6</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312227_MIroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Mumbai Indians</h2>
 </div>
 </td>
 <td>₹10,00,000</td>
 <td>8</td>
 <td>25</td>
 </tr>,
 <tr>
 <td>7</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312239_PBKSroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Punjab Kings</h2>
 </div>
 </td>
 <td>₹3,45,00,000</td>
 <td>7</td>
 <td>25</td>
 </tr>,
 <tr>
 <td>8</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312268_RRroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Rajasthan Royals</h2>
 </div>
 </td>
 <td>₹95,00,000</td>
 <td>8</td>
 <td>24</td>
 </tr>,
 <tr>
 <td>9</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312253_RCBroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Royal Challengers Bangalore</h2>
 </div>
 </td>
 <td>₹1,55,00,000</td>
 <td>8</td>
 <td>22</td>
 </tr>,
 <tr>
 <td>10</td>
 <td class="ih-t-color">
 <div class="ih-pt-ic">
 <div class="ih-pt-img" style="width: 60px">
 <img alt="" src="https://documents.iplt20.com/ipl/franchises/1644312281_SRHroundbig.png"/>
 </div>
 <h2 class="ih-pt-cont">Sunrisers Hyderabad</h2>
 </div>
 </td>
 <td>₹10,00,000</td>
 <td>8</td>
 <td>23</td>
 </tr>]

In [52]:
header=[]
for i in rows:
    cols = i.find_all("td")
    #print(cols)
    sales=[p.text for p in cols]
    print(sales)

[]
['1', '\n\n\n\n\nChennai Super Kings\n\n', '₹2,95,00,000', '8', '25']
['2', '\n\n\n\n\nDelhi Capitals\n\n', '₹10,00,000', '7', '24']
['3', '\n\n\n\n\nGujarat Titans\n\n', '₹15,00,000', '8', '23']
['4', '\n\n\n\n\nKolkata Knight Riders\n\n', '₹45,00,000', '8', '25']
['5', '\n\n\n\n\nLucknow Super Giants\n\n', '₹0', '7', '21']
['6', '\n\n\n\n\nMumbai Indians\n\n', '₹10,00,000', '8', '25']
['7', '\n\n\n\n\nPunjab Kings\n\n', '₹3,45,00,000', '7', '25']
['8', '\n\n\n\n\nRajasthan Royals\n\n', '₹95,00,000', '8', '24']
['9', '\n\n\n\n\nRoyal Challengers Bangalore\n\n', '₹1,55,00,000', '8', '22']
['10', '\n\n\n\n\nSunrisers Hyderabad\n\n', '₹10,00,000', '8', '23']

In [53]:
header=[]
for i in rows:
    cols = i.find_all("td")
    #print(cols)
    sales=[p.text for p in cols]
    header.append(sales)
print(header)

[[], ['1', '\n\n\n\n\nChennai Super Kings\n\n', '₹2,95,00,000', '8', '25'], ['2', '\n\n\n\n\nDelhi Capitals\n\n', '₹10,00,000', '7', '24'], ['3', '\n\n\n\n\nGujarat Titans\n\n', '₹15,00,000', '8', '23'], ['4', '\n\n\n\n\nKolkata Knight Riders\n\n', '₹45,00,000', '8', '25'], ['5', '\n\n\n\n\nLucknow Super Giants\n\n', '₹0', '7', '21'], ['6', '\n\n\n\n\nMumbai Indians\n\n', '₹10,00,000', '8', '25'], ['7', '\n\n\n\n\nPunjab Kings\n\n', '₹3,45,00,000', '7', '25'], ['8', '\n\n\n\n\nRajasthan Royals\n\n', '₹95,00,000', '8', '24'], ['9', '\n\n\n\n\nRoyal Challengers Bangalore\n\n', '₹1,55,00,000', '8', '22'], ['10', '\n\n\n\n\nSunrisers Hyderabad\n\n', '₹10,00,000', '8', '23']]

In [56]:
header.pop(0)

[]

In [57]:
header

[['1', '\n\n\n\n\nChennai Super Kings\n\n', '₹2,95,00,000', '8', '25'],
 ['2', '\n\n\n\n\nDelhi Capitals\n\n', '₹10,00,000', '7', '24'],
 ['3', '\n\n\n\n\nGujarat Titans\n\n', '₹15,00,000', '8', '23'],
 ['4', '\n\n\n\n\nKolkata Knight Riders\n\n', '₹45,00,000', '8', '25'],
 ['5', '\n\n\n\n\nLucknow Super Giants\n\n', '₹0', '7', '21'],
 ['6', '\n\n\n\n\nMumbai Indians\n\n', '₹10,00,000', '8', '25'],
 ['7', '\n\n\n\n\nPunjab Kings\n\n', '₹3,45,00,000', '7', '25'],
 ['8', '\n\n\n\n\nRajasthan Royals\n\n', '₹95,00,000', '8', '24'],
 ['9', '\n\n\n\n\nRoyal Challengers Bangalore\n\n', '₹1,55,00,000', '8', '22'],
 ['10', '\n\n\n\n\nSunrisers Hyderabad\n\n', '₹10,00,000', '8', '23']]

In [86]:
SR_NO=[]
TEAM=[]
FUNDS_REMAINING=[]
OVERSEAS_PLAYERS=[]
TOTAL_PLAYERS=[]
for i in header:
    SR_NO.append(i[0])
    TEAM.append(i[1])
    FUNDS_REMAINING.append(i[2])
    OVERSEAS_PLAYERS.append(i[3])
    TOTAL_PLAYERS.append(i[4])

In [78]:
SR_NO

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [87]:
TEAM

['\n\n\n\n\nChennai Super Kings\n\n',
 '\n\n\n\n\nDelhi Capitals\n\n',
 '\n\n\n\n\nGujarat Titans\n\n',
 '\n\n\n\n\nKolkata Knight Riders\n\n',
 '\n\n\n\n\nLucknow Super Giants\n\n',
 '\n\n\n\n\nMumbai Indians\n\n',
 '\n\n\n\n\nPunjab Kings\n\n',
 '\n\n\n\n\nRajasthan Royals\n\n',
 '\n\n\n\n\nRoyal Challengers Bangalore\n\n',
 '\n\n\n\n\nSunrisers Hyderabad\n\n']

In [62]:
FUNDS_REMAINING

['₹2,95,00,000',
 '₹10,00,000',
 '₹15,00,000',
 '₹45,00,000',
 '₹0',
 '₹10,00,000',
 '₹3,45,00,000',
 '₹95,00,000',
 '₹1,55,00,000',
 '₹10,00,000']

In [96]:
data={"SR_NO":SR_NO,"TEAM":TEAM,"FUNDS_REMAINING":FUNDS_REMAINING,"OVERSEAS_PLAYERS":OVERSEAS_PLAYERS,"TOTAL_PLAYERS":TOTAL_PLAYERS}
data

{'SR_NO': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
 'TEAM': ['\n\n\n\n\nChennai Super Kings\n\n',
  '\n\n\n\n\nDelhi Capitals\n\n',
  '\n\n\n\n\nGujarat Titans\n\n',
  '\n\n\n\n\nKolkata Knight Riders\n\n',
  '\n\n\n\n\nLucknow Super Giants\n\n',
  '\n\n\n\n\nMumbai Indians\n\n',
  '\n\n\n\n\nPunjab Kings\n\n',
  '\n\n\n\n\nRajasthan Royals\n\n',
  '\n\n\n\n\nRoyal Challengers Bangalore\n\n',
  '\n\n\n\n\nSunrisers Hyderabad\n\n'],
 'FUNDS_REMAINING': ['₹2,95,00,000',
  '₹10,00,000',
  '₹15,00,000',
  '₹45,00,000',
  '₹0',
  '₹10,00,000',
  '₹3,45,00,000',
  '₹95,00,000',
  '₹1,55,00,000',
  '₹10,00,000'],
 'OVERSEAS_PLAYERS': ['8', '7', '8', '8', '7', '8', '7', '8', '8', '8'],
 'TOTAL_PLAYERS': ['25', '24', '23', '25', '21', '25', '25', '24', '22', '23']}

In [66]:
import pandas as pd

In [76]:
df=pd.DataFrame(data)
df

,SR_NO,TEAM,FUNDS_REMAINING,OVERSEAS_PLAYERS,TOTAL_PLAYERS
0,1,\n\n\n\n\nChennai Super Kings\n\n,"₹2,95,00,000",8,25
1,2,\n\n\n\n\nDelhi Capitals\n\n,"₹10,00,000",7,24
2,3,\n\n\n\n\nGujarat Titans\n\n,"₹15,00,000",8,23
3,4,\n\n\n\n\nKolkata Knight Riders\n\n,"₹45,00,000",8,25
4,5,\n\n\n\n\nLucknow Super Giants\n\n,₹0,7,21
5,6,\n\n\n\n\nMumbai Indians\n\n,"₹10,00,000",8,25
6,7,\n\n\n\n\nPunjab Kings\n\n,"₹3,45,00,000",7,25
7,8,\n\n\n\n\nRajasthan Royals\n\n,"₹95,00,000",8,24
8,9,\n\n\n\n\nRoyal Challengers Bangalore\n\n,"₹1,55,00,000",8,22
9,10,\n\n\n\n\nSunrisers Hyderabad\n\n,"₹10,00,000",8,23

In [97]:
df.to_csv("IPL 2022.csv")

In [98]:
df

,SR_NO,TEAM,FUNDS_REMAINING,OVERSEAS_PLAYERS,TOTAL_PLAYERS
0,1,\n\n\n\n\nChennai Super Kings\n\n,"₹2,95,00,000",8,25
1,2,\n\n\n\n\nDelhi Capitals\n\n,"₹10,00,000",7,24
2,3,\n\n\n\n\nGujarat Titans\n\n,"₹15,00,000",8,23
3,4,\n\n\n\n\nKolkata Knight Riders\n\n,"₹45,00,000",8,25
4,5,\n\n\n\n\nLucknow Super Giants\n\n,₹0,7,21
5,6,\n\n\n\n\nMumbai Indians\n\n,"₹10,00,000",8,25
6,7,\n\n\n\n\nPunjab Kings\n\n,"₹3,45,00,000",7,25
7,8,\n\n\n\n\nRajasthan Royals\n\n,"₹95,00,000",8,24
8,9,\n\n\n\n\nRoyal Challengers Bangalore\n\n,"₹1,55,00,000",8,22
9,10,\n\n\n\n\nSunrisers Hyderabad\n\n,"₹10,00,000",8,23